// שורשים – main app: loading data, rendering text, word panel.
(function () {
  const $ = (id) => document.getElementById(id);
  const state = {
    books: [],
    book: null, // loaded book JSON
    chapter: 0,
    lexicon: null,
    glosses: {}, // Hebrew glosses generated by a language model (optional file)
    selected: null,
    panel: null, // "word" | "verse"
    panelVerse: null, // verse shown in the commentaries tab
    view: "read",
    opts: loadOpts(),
  };
  const bookCache = {};
  const rootKeyCache = {};

  // ------------------------------------------------------------ helpers

  function loadOpts() {
    const defaults = { teamim: false, segments: true, size: 28, commentator: "Rashi" };
    try {
      return Object.assign(defaults, JSON.parse(localStorage.getItem("roots-opts") || "{}"));
    } catch (e) {
      return defaults;
    }
  }
  function saveOpts() {
    try { localStorage.setItem("roots-opts", JSON.stringify(state.opts)); } catch (e) { /* ignore */ }
  }

  const TEAMIM = /[֑-ֽׅ֯ׄ]/g;
  function clean(text) {
    const t = text.replace(/\//g, "");
    return state.opts.teamim ? t : t.replace(TEAMIM, "");
  }
  function cleanSeg(text) {
    return state.opts.teamim ? text : text.replace(TEAMIM, "");
  }

  function hebNum(n) {
    const ones = ["", "א", "ב", "ג", "ד", "ה", "ו", "ז", "ח", "ט"];
    const tens = ["", "י", "כ", "ל", "מ", "נ", "ס", "ע", "פ", "צ"];
    const hundreds = ["", "ק", "ר", "ש", "ת"];
    let s = "";
    while (n >= 400) { s += "ת"; n -= 400; }
    s += hundreds[Math.floor(n / 100)];
    n %= 100;
    if (n === 15) return s + "טו";
    if (n === 16) return s + "טז";
    return s + tens[Math.floor(n / 10)] + ones[n % 10];
  }

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  }

  function mainLemmaOf(lemma) {
    const parts = lemma.replace(/\s+/g, "").replace(/\+/g, "").split("/");
    return parts[parts.length - 1];
  }

  function rootKeysFor(lemma, morph) {
    if (!lemma) return [];
    const main = mainLemmaOf(lemma);
    if (!(main in rootKeyCache)) {
      const entry = state.lexicon[main];
      const codes = morph.slice(1).split("/");
      const mainCode = codes[Math.min(lemma.split("/").length - 1, codes.length - 1)];
      rootKeyCache[main] = Roots.rootOpinions(entry, mainCode).roots.map((r) => r.key);
    }
    return rootKeyCache[main];
  }

  // ------------------------------------------------------------ loading

  async function getJSON(url) {
    const res = await fetch(url);
    if (!res.ok) throw new Error(url + ": " + res.status);
    return res.json();
  }

  async function loadBook(code) {
    if (!bookCache[code]) bookCache[code] = getJSON("data/books/" + code + ".json");
    return bookCache[code];
  }

  function parseHash() {
    const m = location.hash.match(/^#([^.]+)\.(\d+)/);
    if (m && state.books.some((b) => b.code === m[1])) return { code: m[1], chapter: +m[2] - 1 };
    let last = null;
    try { last = JSON.parse(localStorage.getItem("roots-last") || "null"); } catch (e) { /* ignore */ }
    if (last && state.books.some((b) => b.code === last.code)) return last;
    return { code: "Ezek", chapter: 0 };
  }

  async function go(code, chapter) {
    const meta = state.books.find((b) => b.code === code);
    chapter = Math.max(0, Math.min(chapter, meta.chapters - 1));
    $("text").innerHTML = '<p class="loading">טוען…</p>';
    state.book = await loadBook(code);
    state.chapter = chapter;
    const hash = "#" + code + "." + (chapter + 1);
    if (state.view === "read" && location.hash !== hash) history.replaceState(null, "", hash);
    try { localStorage.setItem("roots-last", JSON.stringify({ code, chapter })); } catch (e) { /* ignore */ }
    fillChapterSelect(meta);
    $("book").value = code;
    $("chapter").value = chapter;
    closePanel();
    renderChapter();
    if (state.view === "read") window.scrollTo(0, 0);
    document.dispatchEvent(new CustomEvent("roots:chapter"));
  }

  // ------------------------------------------------------------ views

  const VIEWS = ["read", "search", "practice"];

  function setView(view, updateHash = true) {
    state.view = view;
    for (const v of VIEWS) {
      $("view-" + v).hidden = v !== view;
      document.querySelector('.tab[data-view="' + v + '"]').classList.toggle("active", v === view);
    }
    document.body.dataset.view = view;
    if (view !== "read") closePanel();
    if (updateHash) {
      const hash = view === "read" && state.book ? "#" + state.book.code + "." + (state.chapter + 1) : "#" + view;
      if (location.hash !== hash) history.pushState(null, "", hash);
    }
    document.dispatchEvent(new CustomEvent("roots:view", { detail: view }));
    window.scrollTo(0, 0);
  }

  /** Open the reader at a word and show its analysis. */
  async function goToWord(code, chapter, v, i, q) {
    setView("read", false);
    if (!state.book || state.book.code !== code || state.chapter !== chapter) await go(code, chapter);
    else history.replaceState(null, "", "#" + code + "." + (chapter + 1));
    showWord(v, i, q);
    const el = $("text").querySelector(".w.selected");
    if (el) el.scrollIntoView({ block: "center" });
  }

  function viewFromHash() {
    const m = location.hash.match(/^#(search|practice)\b/);
    return m ? m[1] : "read";
  }

  // ------------------------------------------------------------ rendering

  function fillBookSelect() {
    const sel = $("book");
    sel.innerHTML = "";
    let group = null;
    for (const b of state.books) {
      if (!group || group.label !== b.section) {
        group = document.createElement("optgroup");
        group.label = b.section;
        sel.appendChild(group);
      }
      const o = document.createElement("option");
      o.value = b.code;
      o.textContent = b.name;
      group.appendChild(o);
    }
  }

  function fillChapterSelect(meta) {
    const sel = $("chapter");
    if (sel.dataset.book === meta.code) return;
    sel.dataset.book = meta.code;
    sel.innerHTML = "";
    for (let i = 0; i < meta.chapters; i++) {
      const o = document.createElement("option");
      o.value = i;
      o.textContent = "פרק " + hebNum(i + 1);
      sel.appendChild(o);
    }
  }

  function wordHTML(word, v, i, q) {
    const [text, lemma, morph] = word;
    let inner;
    if (state.opts.segments && morph && text.includes("/")) {
      const a = Morph.analyzeWord(text, lemma, morph);
      inner = a.segments
        .map((s) => (s.role === "main" ? esc(cleanSeg(s.text)) : '<span class="seg-' + s.role + '">' + esc(cleanSeg(s.text)) + "</span>"))
        .join("");
    } else {
      inner = esc(clean(text));
    }
    return '<span class="w" tabindex="0" data-v="' + v + '" data-i="' + i + '" data-q="' + q + '">' + inner + "</span>";
  }

  function sepHTML(sep) {
    if (!sep) return " ";
    let out = "";
    for (const ch of sep) {
      if (ch === "־") out += "־";
      else if (ch === "׃") out += "׃ ";
      else if (ch === "׀") out += " ׀ ";
      else if (ch === "פ") out += '<span class="petucha" title="פרשה פתוחה"></span>';
      else if (ch === "ס") out += '<span class="setuma" title="פרשה סתומה">ס</span> ';
    }
    return out.endsWith("־") || out.endsWith(" ") || out.endsWith("</span>") ? out : out + " ";
  }

  function renderChapter() {
    const verses = state.book.chapters[state.chapter];
    const parts = ["<h2>" + esc(state.book.name) + " פרק " + hebNum(state.chapter + 1) + "</h2>"];
    verses.forEach((tokens, v) => {
      parts.push('<span class="verse-num" role="button" tabindex="0" data-verse="' + v + '" title="מפרשים על הפסוק">' + hebNum(v + 1) + "</span>");
      tokens.forEach((tok, i) => {
        const qere = tok[4];
        if (qere) {
          qere.forEach((qw, qi) => {
            parts.push(wordHTML(qw, v, i, qi));
            if (qi < qere.length - 1) parts.push(" ");
          });
          if (tok[0]) parts.push('<span class="ketiv" title="כתיב">(' + esc(tok[0].replace(/\//g, "")) + ")</span>");
        } else {
          parts.push(wordHTML(tok, v, i, -1));
        }
        parts.push(sepHTML(tok[3]));
      });
    });
    const el = $("text");
    el.innerHTML = parts.join("");
    el.classList.toggle("show-segments", state.opts.segments);
    document.documentElement.style.setProperty("--text-size", state.opts.size + "px");
    if (state.selected) highlight(state.selected);
    markVerse();
  }

  function getWord(v, i, q) {
    const tok = state.book.chapters[state.chapter][v][i];
    return { tok, word: q >= 0 ? tok[4][q] : tok };
  }

  // ------------------------------------------------------------ panel

  function highlight(sel) {
    const text = $("text");
    text.querySelectorAll(".w.selected, .w.same-root").forEach((e) => e.classList.remove("selected", "same-root"));
    const { word } = getWord(sel.v, sel.i, sel.q);
    const keys = rootKeysFor(word[1], word[2]);
    let count = 0;
    text.querySelectorAll(".w").forEach((el) => {
      const v = +el.dataset.v, i = +el.dataset.i, q = +el.dataset.q;
      if (v === sel.v && i === sel.i && q === sel.q) {
        el.classList.add("selected");
        return;
      }
      if (!keys.length) return;
      const w = getWord(v, i, q).word;
      const k2 = rootKeysFor(w[1], w[2]);
      if (k2.some((k) => keys.includes(k))) {
        el.classList.add("same-root");
        count++;
      }
    });
    return count;
  }

  function closePanel() {
    state.selected = null;
    state.panel = null;
    state.panelVerse = null;
    markVerse();
    $("panel").hidden = true;
    document.querySelector(".layout").classList.remove("with-panel");
    document.body.classList.remove("panel-open");
    $("text").querySelectorAll(".w.selected, .w.same-root").forEach((e) => e.classList.remove("selected", "same-root"));
    if (window.Cheat) Cheat.clearFocus();
  }

  const ROLE = { prefix: "תחילית", main: "בסיס", suffix: "סופית" };

  function showWord(v, i, q) {
    state.selected = { v, i, q };
    state.panel = "word";
    state.panelVerse = v;
    markVerse();
    const { tok, word } = getWord(v, i, q);
    const [text, lemma, morph] = word;
    const sameRootCount = highlight(state.selected);
    const a = Morph.analyzeWord(text, lemma, morph);
    const entry = state.lexicon[a.mainLemma];
    const { roots, reason, strongNote } = Roots.rootOpinions(entry, a.main.code);
    const ref = state.book.name + " " + hebNum(state.chapter + 1) + ", " + hebNum(v + 1);

    const h = [panelTabs("word")];
    h.push('<p class="word-title">' + esc(clean(text)) + "</p>");
    h.push('<div class="word-ref">' + esc(ref) + (a.lang === "A" ? " · ארמית" : "") +
      ' · <button type="button" class="link" data-cheat="">בלוח העזר</button></div>');
    const he = state.glosses[a.mainLemma];
    if (he) {
      h.push('<p class="gloss-he"><b>' + esc(he.g) + '</b> <span class="ai-badge" title="הפירוש נוצר אוטומטית בעזרת מודל שפה, על סמך המילונים BDB וסטרונג. ייתכנו טעויות.">פירוש ממוחשב</span>' +
        (he.n ? '<span class="gloss-note">' + esc(he.n) + "</span>" : "") + "</p>");
    }

    if (q >= 0) {
      h.push('<p class="muted">' + (tok[0]
        ? "כתיב וקרי: בכתוב <span class=\"heb-inline\">" + esc(tok[0].replace(/\//g, "")) + "</span>, וקוראים <span class=\"heb-inline\">" + esc(tok[4].map((w) => clean(w[0])).join(" ")) + "</span>. הניתוח הוא של הקרי."
        : "קרי ולא כתיב: מילה שנקראת אף שאינה כתובה בטקסט.") + "</p>");
    }

    // --- word structure
    h.push("<h3>פירוק המילה</h3><div class=\"segments\">");
    for (const s of a.segments) {
      h.push('<div class="segment ' + s.role + '"><div class="seg-text">' + esc(cleanSeg(s.text)) + "</div><div>" +
        '<div class="seg-title">' + esc(s.title) + '<span class="seg-role">' + ROLE[s.role] + "</span></div>" +
        (s.details.length ? '<div class="seg-details">' + esc(s.details.join(", ")) + "</div>" : "") +
        "</div></div>");
    }
    h.push("</div>");

    // --- roots
    h.push("<h3>השורש</h3>");
    if (roots.length > 1) {
      h.push('<p class="consensus">יש כמה דעות לגבי שורש המילה:</p>');
    } else if (roots.length === 1 && roots[0].sources.length > 1) {
      h.push('<p class="consensus">המילונים מסכימים על השורש.</p>');
    }
    for (const r of roots) {
      h.push('<div class="root-card"><div class="root-head"><span class="root-letters">' + esc(Roots.displayRoot(r.root)) + "</span>" +
        '<button type="button" class="link" data-root="' + esc(r.root) + '">כל המילים מהשורש בתנ"ך ←</button></div>');
      h.push('<ul class="sources">');
      for (const s of r.sources) {
        const bits = [];
        if (s.path && s.path.length) bits.push("נגזר מ: <span class=\"heb-inline\">" + esc(s.path.join(" ← ")) + "</span>");
        if (s.via) bits.push("דרך <span class=\"heb-inline\">" + esc(s.via) + "</span>");
        if (s.unattested) bits.push(esc(s.unattested));
        let badges = '<span class="badge" title="' + esc(s.full) + '">' + esc(s.name) + "</span>";
        if (s.uncertain) badges += '<span class="badge warn">משוער</span>';
        if (s.cognate) badges += '<span class="badge warn">מקביל עברי</span>';
        h.push("<li>" + badges + bits.join(" · ") + (s.def ? '<div class="root-def">' + esc(s.def) + "</div>" : "") + "</li>");
      }
      h.push("</ul>");
      const gz = Roots.gizrot(r.root);
      if (gz.length) {
        h.push('<ul class="gizra">' + gz.map(([name, expl]) => "<li><b>" + esc(name) + ":</b> " + esc(expl) + "</li>").join("") + "</ul>");
      }
      h.push("</div>");
    }
    if (strongNote) h.push('<p class="muted"><span class="badge">Strong</span>' + esc(strongNote) + "</p>");
    if (!roots.length) h.push('<p class="muted">' + esc(reason) + "</p>");
    if (roots.length) {
      h.push('<p class="root-count">' + (sameRootCount
        ? "מילים נוספות מאותו שורש בפרק: <b>" + sameRootCount + "</b> (מסומנות בטקסט)."
        : "אין בפרק זה מילים נוספות מאותו שורש.") + "</p>");
    }

    // --- noun pattern
    const mishkal = window.Cheat ? Cheat.mishkalFor(entry, roots, a.main.code) : null;
    if (mishkal) {
      h.push("<h3>משקל</h3><p class=\"mishkal\">" + '<b class="heb-inline">' + esc(mishkal.item.name) + "</b> " +
        '<span class="muted">(' + esc(mishkal.group.title) + ", לפי צורת המילון <span class=\"heb-inline\">" + esc(clean(entry.w)) + "</span>; זיהוי אוטומטי)</span> " +
        '<button type="button" class="link" data-cheat="' + mishkal.item.id + '">בלוח העזר ←</button></p>');
    }

    // --- grammar notes
    const notes = a.segments.flatMap((s) => s.notes);
    if (notes.length) {
      h.push("<h3>הסבר דקדוקי</h3><ul class=\"notes\">");
      for (const [t, e] of notes) h.push("<li><b>" + esc(t) + ":</b> " + esc(e) + "</li>");
      h.push("</ul>");
    }

    // --- dictionary
    if (entry) {
      h.push("<h3>מילון</h3><div class=\"lex\">");
      h.push('<div><span class="heb-inline">' + esc(entry.w) + "</span>" + (entry.strong ? ' <span class="muted">(Strong H' + esc(entry.strong.n) + ")</span>" : "") + "</div>");
      if (he) h.push('<div>פירוש: ' + esc(he.g) + "</div>");
      if (entry.def) h.push('<div class="gloss">BDB: ' + esc(entry.def) + "</div>");
      if (entry.strong && entry.strong.def) h.push('<div class="gloss">Strong: ' + esc(entry.strong.def) + "</div>");
      if (entry.strong && entry.strong.src) h.push('<div class="gloss muted">Strong derivation: ' + esc(entry.strong.src) + "</div>");
      h.push("</div>");
    }
    h.push('<div id="word-comm" hidden></div>');
    h.push('<p class="muted">קוד ניתוח: <code dir="ltr">' + esc(morph) + "</code> · למה: <code dir=\"ltr\">" + esc(lemma) + "</code></p>");

    $("panel-body").innerHTML = h.join("");
    if (window.Cheat) Cheat.focusWord({ analysis: a, roots, entry, mishkal, label: clean(text) });
    openPanel();
    loadWordComments(v, text, a);
    if (window.matchMedia("(max-width: 900px)").matches) {
      // On phones the panel is a bottom sheet: keep the chosen word visible above it.
      const el = $("text").querySelector(".w.selected");
      if (el) {
        const top = el.getBoundingClientRect().top;
        const want = window.innerHeight * 0.2;
        if (top > window.innerHeight * 0.38 || top < 60) window.scrollBy({ top: top - want, behavior: "smooth" });
      }
    }
  }

  function openPanel() {
    $("panel").hidden = false;
    $("panel").scrollTop = 0;
    document.querySelector(".layout").classList.add("with-panel");
    document.body.classList.add("panel-open");
  }

  /** Tabs at the top of the panel: the selected word's analysis / commentaries on its verse. */
  function panelTabs(active) {
    const sel = state.selected;
    const hasWord = sel && sel.v === state.panelVerse;
    if (!hasWord) return "";
    const tab = (id, label) => '<button type="button" class="ptab' + (id === active ? " active" : "") + '" data-ptab="' + id + '">' + label + "</button>";
    return '<div class="panel-tabs" role="tablist">' + tab("word", "ניתוח המילה") + tab("verse", "מפרשים על הפסוק") + "</div>";
  }

  function markVerse() {
    $("text").querySelectorAll(".verse-num.active").forEach((e) => e.classList.remove("active"));
    if (state.panel !== "verse") return;
    const el = $("text").querySelector('.verse-num[data-verse="' + state.panelVerse + '"]');
    if (el) el.classList.add("active");
  }

  function verseText(v) {
    return state.book.chapters[state.chapter][v]
      .map((tok) => (tok[4] ? tok[4].map((w) => clean(w[0])).join(" ") : clean(tok[0])) + (tok[3] && tok[3].includes("־") ? "־" : " "))
      .join("").replace(/\s+/g, " ").trim();
  }

  let panelToken = 0;

  /** Commentaries (from Sefaria) on verse v of the current chapter. */
  async function showVerse(v, workId) {
    const verses = state.book.chapters[state.chapter];
    v = Math.max(0, Math.min(v, verses.length - 1));
    if (state.selected && state.selected.v !== v) {
      state.selected = null;
      $("text").querySelectorAll(".w.selected, .w.same-root").forEach((e) => e.classList.remove("selected", "same-root"));
      if (window.Cheat) Cheat.clearFocus();
    }
    state.panel = "verse";
    state.panelVerse = v;
    if (workId) { state.opts.commentator = workId; saveOpts(); }
    markVerse();
    const token = ++panelToken;
    const code = state.book.code, ch = state.chapter;
    const ref = state.book.name + " " + hebNum(ch + 1) + ", " + hebNum(v + 1);
    const head = [panelTabs("verse")];
    head.push('<div class="verse-head"><button type="button" class="icon" data-verse-step="-1" title="הפסוק הקודם" aria-label="הפסוק הקודם"' + (v ? "" : " disabled") + '>›</button>' +
      '<span class="verse-title">' + esc(ref) + "</span>" +
      '<button type="button" class="icon" data-verse-step="1" title="הפסוק הבא" aria-label="הפסוק הבא"' + (v < verses.length - 1 ? "" : " disabled") + ">‹</button></div>");
    head.push('<p class="verse-text">' + esc(verseText(v)) + "</p>");
    const body = $("panel-body");
    const sefLink = '<a href="' + esc(Sefaria.sefariaLink(Sefaria.verseRef(code, ch, v))) + '" target="_blank" rel="noopener">הפסוק בספריא ←</a>';
    body.innerHTML = head.join("") + '<p class="loading small">טוען מפרשים מספריא…</p>';
    openPanel();

    let groups;
    try {
      groups = (await Sefaria.chapterLinks(code, ch)).filter((g) => g.verses[v + 1]);
    } catch (err) {
      if (token !== panelToken) return;
      body.innerHTML = head.join("") + '<p class="error small">לא ניתן לטעון מפרשים מספריא (' + esc(err.message) + '). ' + sefLink + "</p>";
      return;
    }
    if (token !== panelToken) return;
    if (!groups.length) {
      body.innerHTML = head.join("") + '<p class="muted">לא נמצאו מפרשים לפסוק זה. ' + sefLink + "</p>";
      return;
    }
    const want = state.opts.commentator;
    const group = groups.find((g) => g.id === want) || groups.find((g) => g.en === want) || groups[0];
    const chips = '<div class="comm-chips" role="tablist" aria-label="מפרשים">' + groups.map((g) =>
      '<button type="button" class="chip' + (g === group ? " active" : "") + '" data-work="' + esc(g.id) + '" title="' + esc(g.id) + '">' + esc(g.he) + "</button>").join("") + "</div>";
    body.innerHTML = head.join("") + chips + '<div class="comm-body"><p class="loading small">טוען…</p></div>';

    const results = await Sefaria.verseComments(group, v + 1);
    if (token !== panelToken) return;
    const out = [];
    const versions = new Map();
    for (const r of results) {
      if (r.failed) continue;
      for (const t of r.texts) out.push('<div class="comm">' + Sefaria.sanitize(t) + "</div>");
      if (r.version && r.version.title) versions.set(r.version.title, r.version);
    }
    const credits = [...versions.values()].map((ver) => esc(ver.title) + (ver.license ? " (" + esc(ver.license) + ")" : "")).join("; ");
    const firstRef = (group.verses[v + 1] || [])[0];
    body.querySelector(".comm-body").innerHTML =
      (out.length ? out.join("") : '<p class="muted">לא ניתן לטעון את הטקסט.</p>') +
      '<p class="muted credit">מתוך <a href="' + esc(Sefaria.sefariaLink(firstRef || Sefaria.verseRef(code, ch, v))) + '" target="_blank" rel="noopener">ספריא</a>' +
      (credits ? " · " + credits : "") + " · " + sefLink + "</p>";
  }

  /** Comments of word-explaining commentators (מצודת ציון, רש"י, רד"ק) whose heading quotes the selected word. */
  async function loadWordComments(v, text, a) {
    const token = ++panelToken;
    const sel = state.selected;
    const forms = [
      Sefaria.plain(text.replace(/\//g, "")),
      Sefaria.plain(a.segments.filter((s) => s.role !== "prefix").map((s) => s.text).join("")),
    ];
    let found = [];
    try {
      const groups = (await Sefaria.chapterLinks(state.book.code, state.chapter))
        .filter((g) => Sefaria.WORD_COMMENTARIES.includes(g.en) && g.verses[v + 1])
        .sort((x, y) => Sefaria.WORD_COMMENTARIES.indexOf(x.en) - Sefaria.WORD_COMMENTARIES.indexOf(y.en));
      const lists = await Promise.all(groups.map((g) => Sefaria.verseComments(g, v + 1)));
      groups.forEach((g, gi) => {
        for (const r of lists[gi]) {
          for (const t of r.texts) {
            if (Sefaria.headingMatches(Sefaria.heading(t), forms)) found.push({ g, t });
          }
        }
      });
    } catch (err) {
      return; // offline or Sefaria unavailable: the section simply stays hidden
    }
    if (token !== panelToken || state.selected !== sel) return;
    const el = $("word-comm");
    if (!el || !found.length) return;
    el.innerHTML = "<h3>בפרשנים</h3>" + found.map(({ g, t }) =>
      '<div class="comm"><span class="badge">' + esc(g.he) + "</span>" + Sefaria.sanitize(t) + "</div>").join("") +
      '<p class="muted">מתוך <a href="https://www.sefaria.org" target="_blank" rel="noopener">ספריא</a> · ' +
      '<button type="button" class="link" data-ptab="verse">כל המפרשים על הפסוק ←</button></p>';
    el.hidden = false;
  }

  // ------------------------------------------------------------ events

  function bind() {
    $("book").addEventListener("change", (e) => go(e.target.value, 0));
    $("chapter").addEventListener("change", (e) => go(state.book.code, +e.target.value));
    $("prev").addEventListener("click", () => step(-1));
    $("next").addEventListener("click", () => step(1));
    $("close-panel").addEventListener("click", closePanel);
    $("panel-body").addEventListener("click", (e) => {
      const pt = e.target.closest("[data-ptab]");
      if (pt) {
        if (pt.dataset.ptab === "verse") showVerse(state.panelVerse);
        else if (state.selected) showWord(state.selected.v, state.selected.i, state.selected.q);
        return;
      }
      const vs = e.target.closest("[data-verse-step]");
      if (vs) { showVerse(state.panelVerse + +vs.dataset.verseStep); return; }
      const wk = e.target.closest("[data-work]");
      if (wk) { showVerse(state.panelVerse, wk.dataset.work); return; }
      const c = e.target.closest("[data-cheat]");
      if (c && window.Cheat) {
        if (c.dataset.cheat) Cheat.show(c.dataset.cheat);
        else Cheat.setOpen(true);
        return;
      }
      const b = e.target.closest("[data-root]");
      if (b && window.Search) {
        document.getElementById("search-scope").value = "all";
        Search.openRoot(b.dataset.root);
      }
    });

    const teamim = $("opt-teamim"), segments = $("opt-segments");
    teamim.checked = state.opts.teamim;
    segments.checked = state.opts.segments;
    teamim.addEventListener("change", () => { state.opts.teamim = teamim.checked; saveOpts(); rerender(); });
    segments.addEventListener("change", () => { state.opts.segments = segments.checked; saveOpts(); rerender(); });
    $("smaller").addEventListener("click", () => resize(-2));
    $("larger").addEventListener("click", () => resize(2));

    const text = $("text");
    const activate = (el) => showWord(+el.dataset.v, +el.dataset.i, +el.dataset.q);
    text.addEventListener("click", (e) => {
      const vn = e.target.closest(".verse-num");
      if (vn) { showVerse(+vn.dataset.verse); return; }
      const el = e.target.closest(".w");
      if (el) activate(el);
    });
    text.addEventListener("keydown", (e) => {
      const vn = e.target.closest(".verse-num");
      if (vn && (e.key === "Enter" || e.key === " ")) { e.preventDefault(); showVerse(+vn.dataset.verse); return; }
      const el = e.target.closest(".w");
      if (el && (e.key === "Enter" || e.key === " ")) { e.preventDefault(); activate(el); }
    });
    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape") closePanel();
    });
    document.querySelectorAll(".tab").forEach((b) => b.addEventListener("click", () => setView(b.dataset.view)));
    window.addEventListener("popstate", onHash);
    window.addEventListener("hashchange", onHash);
  }

  function onHash() {
    const view = viewFromHash();
    if (view !== state.view) setView(view, false);
    if (view === "read") {
      const t = parseHash();
      if (!state.book || t.code !== state.book.code || t.chapter !== state.chapter) go(t.code, t.chapter);
    }
  }

  function rerender() {
    const sel = state.selected, panel = state.panel, pv = state.panelVerse;
    renderChapter();
    if (panel === "verse") showVerse(pv);
    else if (sel) showWord(sel.v, sel.i, sel.q);
  }

  function resize(d) {
    state.opts.size = Math.max(18, Math.min(48, state.opts.size + d));
    saveOpts();
    document.documentElement.style.setProperty("--text-size", state.opts.size + "px");
  }

  async function step(d) {
    const idx = state.books.findIndex((b) => b.code === state.book.code);
    let ch = state.chapter + d;
    if (ch < 0 && idx > 0) return go(state.books[idx - 1].code, state.books[idx - 1].chapters - 1);
    if (ch >= state.books[idx].chapters && idx < state.books.length - 1) return go(state.books[idx + 1].code, 0);
    return go(state.book.code, ch);
  }

  async function init() {
    bind();
    try {
      const [books, lexicon] = await Promise.all([getJSON("data/books.json"), getJSON("data/lexicon.json")]);
      state.books = books;
      state.lexicon = lexicon;
      // Hebrew glosses are optional: the site works (with English only) without them.
      getJSON("data/glosses-he.json").then((g) => {
        state.glosses = g;
        if (state.selected && state.panel === "word") showWord(state.selected.v, state.selected.i, state.selected.q);
      }).catch(() => {});
      fillBookSelect();
      const t = parseHash();
      const view = viewFromHash();
      state.view = view;
      await go(t.code, t.chapter);
      setView(view, false);
    } catch (err) {
      $("text").innerHTML = '<p class="error">שגיאה בטעינת הנתונים: ' + esc(err.message) +
        "<br>יש להריץ את האתר דרך שרת (למשל <code dir=\"ltr\">python3 -m http.server</code>) ולא ישירות מהקובץ.</p>";
    }
  }

  window.App = {
    state, go, goToWord, setView, getJSON, loadBook, hebNum, esc, clean, cleanSeg,
    mainLemmaOf, rootKeysFor, gloss: (lemma) => state.glosses[lemma],
  };

  init();
})();
